export const SERVER_URL = 'http://localhost:3000';
export const WS_SERVER_URL = 'http://localhost:3001/';
export const STATE_STATUS = {
    WAITING: 'WAITING_FOR_PLAYERS',
    STARTED: 'GAME_STARTED',
    FINISHED: 'GAME_FINISHED'
};
export const STORAGE_KEYS = {
    GAME: 'GAME_ID',
    PLAYER: 'PLAYER_ID',
    STATE: 'STATE_STATUS',
    CAN_DEACTIVATE_GAME_ROOM: 'CAN_DEACTIVATE_GAME_ROOM',
    CAN_DEACTIVATE_SCORE_TABLE_ROOM: 'CAN_DEACTIVATE_SCORE_TABLE_ROOM'
};